services:
  server:
    build:
      context: ../..
      dockerfile: infrastructure/docker/server.Dockerfile
    env_file:
      - ../../.env
    ports:
      - "3000:3000"

  web:
    build:
      context: ../..
      dockerfile: infrastructure/docker/web.Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - server
